### PR TITLE
Feat: Added note color, note priorities

### PR DESCRIPTION
**Pull request by bharati-21**
- User can add/ edit the note color
- User can add/ edit priorities
- Users can filter by priorities
- Users can sort on priorities

Deploy Preview - https://deploy-preview-8--inscribe-notes.netlify.app/

### CODE REVIEW

**Review by sonishreyas — APPROVED** [review]
Code looks good and the app looks really good. You can use preetier at few places. Rest looks good.

**Review by vidhi-thakur — APPROVED** [review]
looks good to merge, you have added css properties keeping in mind other browsers as well which is nice 👍

**Comment by bharati-21** [comment]
> Code looks good and the app looks really good. You can use preetier at few places. Rest looks good.

Yes, I am not sure why the prettier isn't working well. Will have to look into it post submission.

Thank you for your review!

**Comment by bharati-21** [comment]
> looks good to merge, you have added css properties keeping in mind other browsers as well which is nice 👍

Thank you for your review!

**Pull request merged**
