### PR TITLE
feat: move to, display, restore from, and delete from trash

### PR DESCRIPTION
**Pull request by bharati-21**
This PR contains the following features:
- Delete notes/ archived notes and move them to the trash
- Display notes in the trash
- Restore notes/ archived notes from trash
- Delete notes from the trash forever.

### CODE REVIEW

**Review by JowelTisso — APPROVED** [review]
* Try to keep your PR small
* Rest Looks Good

**Review by manish591 — APPROVED** [review]
Code is looking good to merge. 
Your naming conventions are good and the code is modular as well.

**Comment by bharati-21** [comment]
> * Try to keep your PR small
> * Rest Looks Good

Yes, I shall keep this in my mind for the future.

Thank you for your review.

**Comment by bharati-21** [comment]
> Code is looking good to merge. Your naming conventions are good and the code is modular as well.

Thank you for your review!

**Pull request merged**
